
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeproj-deployment
  labels:
    app: nodeproj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeproj
  template:
    metadata:
      labels:
        app: nodeproj 
    spec:
      containers:
      - name: nodeserver
        image: evelynym/nodeproj:latest
        ports:
        - containerPort: 3003
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeproj-service
spec:
  selector:
    app: nodeproj 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3003
    nodePort: 31110
